Repository projetoKhali/api4front, pull requests merged in 2024-06, with the labels that each got.

#107 feat: added notifications
  src/components/form/FormPopup.vue
  src/components/popup/NotificationPopup.vue
  src/components/popup/Popup.vue
  src/service/PartnerService.ts
  src/views/ComparativePartner.vue
  src/views/ComparativeTracks.vue
  src/views/ExportTrackReport.vue
  src/views/ListPartner.vue
  src/views/ListUser.vue
  src/views/PartnerDashboard.vue
  src/views/PopupExample.vue
  src/views/PopupNotifExample.vue
  src/views/TrackDashboard.vue
Labels: Component

#109 Fixes
  src/report/track.ts
  src/schemas/User.ts
  src/schemas/partner/PartnerExpertise.ts
  src/schemas/partner/PartnerMetric.ts
  src/schemas/partner/PartnerTrack.ts
  src/service/PartnerMetricsService.ts
  src/service/PartnerService.ts
  src/service/TrackMetricService.ts
  src/service/TrackMetricsService.ts
  src/service/UserService.ts
  src/util/util.ts
  src/views/ComparativePartner.vue
  src/views/ComparativeTracks.vue
  src/views/ExportTrackReport.vue
  src/views/FilterTest.vue
  src/views/ListUser.vue
  src/views/PopupExample.vue
Labels: bug

#112 fix: parsing de `PartnerReportSchema`
  src/service/PartnerReportService.ts
Labels: bug, Schemas, Partner, Service

#111 fix: count qualifiers in dash track
  src/views/TrackDashboard.vue
Labels: bug
