Repository projetoKhali/api4front, pull requests merged in 2024-05, with the labels that each got.

#54 update `pull_request_template`
  .github/pull_request_template.md
Labels: DX

#56 feat: add page-counter on table
  src/components/Table.vue
Labels: Component, View

#58 Componente de formulário
  src/components/form/Form.vue
  src/components/form/UserForm.vue
  src/router/index.ts
  src/schemas/user.ts
  src/views/FormExample.vue
Labels: Component

#84 Pages dashboard
  src/router/index.ts
  src/schemas/User.ts
  src/views/ComparativePartner.vue
Labels: Partner, Track

#91 fix: hide logic in `router` and `NavBar` component
  src/components/NavBar.vue
  src/router/index.ts
Labels: bug
