Repository projetoKhali/api4front, pull requests merged in 2024-04, with the labels that each got.

#14 Configuração de estilo de código
  .editorconfig
  .eslintignore
  .eslintrc.yml
  .gitignore
  .lintstagedrc.json
  .markdownlint.yml
  .prettierrc.yml
  .yamllint.yml
  .yarnrc.yml
  package.json
  src/App.vue
  src/assets/vue.svg
  src/components/HelloWorld.vue
  src/main.ts
  src/views/example.vue
  yarn.lock
Labels: DX

#45 fix: funções service | style: componentes
  src/components/CountCard.vue
  src/components/StatCircle.vue
  src/components/Table.vue
  src/schemas/user.ts
  src/service/PartnerService.ts
  src/service/TrackService.ts
Labels: bug, Partner, Track, Service

#48 feat: add pagination on table component
  src/components/CountCard.vue
  src/components/Table.vue
Labels: Component
